### ISSUE TITLE
Error: Failed to get status

### ISSUE THREAD

**Issue by litevsky** [derek-miller/homebridge-wattbox#6]
Keep getting "[Wattbox] Failed to get the status from the wattbox; verify IP address, username, and password are correct" error.
Using a WB-300-IP-3 firmware WB10.B929. The latest firmware update did mention some authentication changes. Not sure if this is related. https://www.control4.com/docs/product/wattbox-300-series/release-notes/english/latest/wattbox-300-series-release-notes-rev-c.pdf

**Logs:**
[2/22/2024, 12:35:26 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 9712) is running on port 51573.
[2/22/2024, 12:35:26 PM] [Wattbox] Failed to get the status from the wattbox; verify IP address, username, and password are correct

**Plugin Config:**

{
    "name": "Wattbox",
    "address": "192.168.4.2",
    "username": "admin",
    "password": "******",
    "includeOutlets": [
        "eero",
        "fiber"
    ],
    "outletStatusCacheTtl": 15,
    "outletStatusPollInterval": 15000,
    "platform": "WattBox"
}
**Screenshots:**

**Environment:**

- **Plugin Version**: 3
- **Homebridge Version**:  1.7
- **Node.js Version**:  18.19.0
- **NPM Version**:  
- **Operating System**:  Rasbian running Docker

**Comment by derek-miller** [comment]
Are you able to log in to the wattbox directly at its IP with the same credentials stored in the driver config?

**Comment by litevsky** [comment]
Yes, I am. I also tried not including any outlets. Reinstalling, etc.

**Comment by derek-miller** [comment]
This should be fixed in v3.0.1. Please reopen if you still see this issue.
