### ISSUE TITLE
Ability to configure reset only outlets

### ISSUE THREAD

**Issue by Hans-Solo-Dolo** [derek-miller/homebridge-wattbox#8]
**Is your feature request related to a problem? Please describe:** 

Currently have a network switch that is configured as network device(reset only) in Wattbox/OVRC. Turning off the outlet through the plugin does nothing as Wattbox limits to reset only

**Describe the solution you'd like:**

Ability to configure certain outlets as RESET ONLY so that we can power cycle those outlets without changing the OVRC configuration

**Describe alternatives you've considered:**

NA

**Additional context:**

NA

**Comment by derek-miller** [comment]
This is fixed in v3.1.0

**Comment by Hans-Solo-Dolo** [comment]
> This is fixed in v3.1.0

Thanks for the quick response!! It looks like it auto configures the reset only outlets with the watt box directly so no input needed from the end-user, is that correct?

**Comment by derek-miller** [comment]
Correct.
